 
   INSERT INTO AUD_TRAMITES_T@DBK_AUDIMED_DBREPLICA 
                                     NOLOGGING (ID_TRAMITE,
    CODI_TRAMITE,
    COORDINACION_PROVINCIAL,
    VAL_SOLICITADO,
    VAL_IVA,
    CODI_PRESTADOR,
    DES_PRESTADOR,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    VAL_APROBADO_FIN,
    VAL_APROBADO_INI,
    VAL_NOACUERDO,
    VAL_NOCONCILIABLE,
    CODI_TIPO_ATEN,
    CODTRAMITE1,
    CAJA,
    OBS_OBJECION,
    OBS_CONCILIACION,
    OBS_NOACUERDO,
    OBS_NOCONCILIABLE,
    FEC_RECEPCION,
    FEC_AUDITORIA_PERTINENCIA,
    USU_AUDITORIA_PERTINENCIA,
    FEC_AUDITORIA_LIQUIDACION,
    USU_AUDITORIA_LIQUIDACION,
    FEC_NOTIFICACION,
    FEC_CONCILIACION,
    USU_CONCILIACION,
    FEC_CIERRE,
    FEC_CALIDAD,
    USU_CALIDAD,
    LOTE_ARCHIVO_IESS,
    CODIGO_ARCHIVO_IESS,
    DESCARGA_PLANILLA,
    NUME_FACTURA,
    VALOR_IVA_APROBADO,
    COD_COORDINACION) 
      SELECT 
            T.ID_TRAMITE,
    CODI_TRAMITE,
    COORDINACION_PROVINCIAL,
    VAL_SOLICITADO,
    VAL_IVA,
    CODI_PRESTADOR,
    DES_PRESTADOR,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    VAL_APROBADO_FIN,
    VAL_APROBADO_INI,
    VAL_NOACUERDO,
    VAL_NOCONCILIABLE,
    CODI_TIPO_ATEN,
    CODTRAMITE1,
    CAJA,
    OBS_OBJECION,
    OBS_CONCILIACION,
    OBS_NOACUERDO,
    OBS_NOCONCILIABLE,
    FEC_RECEPCION,
    FEC_AUDITORIA_PERTINENCIA,
    USU_AUDITORIA_PERTINENCIA,
    FEC_AUDITORIA_LIQUIDACION,
    USU_AUDITORIA_LIQUIDACION,
    FEC_NOTIFICACION,
    FEC_CONCILIACION,
    USU_CONCILIACION,
    FEC_CIERRE,
    FEC_CALIDAD,
    USU_CALIDAD,
    LOTE_ARCHIVO_IESS,
    CODIGO_ARCHIVO_IESS,
    DESCARGA_PLANILLA,
    NUME_FACTURA,
    VALOR_IVA_APROBADO,
    COD_COORDINACIONf
        FROM AUD_TRAMITES_T T1
        WHERE NOT EXISTS (SELECT  X1 FROM AUD_EPLICA X2 WHERE X.ID_TRAMITE = T.ID_TRAMITE);

   L_TRAMITES := SQL%ROWCOUNT;
   INSERT INTO AUD_VISOR_LOG_USUARIOS_T@DBK_AUDIMED_DBREPLICA (ID_LOG_USUARIO, ACCION,RESULTADO,DETALLE,USU_CREACION,FEC_CREACION,IP_EQUIPO,TABLA)
   VALUES(AUD_VISOR_LOG_USUARIOS_S.NEXTVAL@DBK_AUDIMED_DBREPLICA, 'REPLICA', 'EXITO', 'REPLICA DE TRAMITES. REGISTROS:' ||TO_CHAR(L_TRAMITES) , 'SYSTEM', SYSDATE, L_IP,'AUD_TRAMITES_T' );

   COMMIT;

  
   INSERT INTO AUD_EXPEDIENTES_T@DBK_AUDIMED_DBREPLICA
                                     NOLOGGING(ID_EXPEDIENTE,
    ID_TRAMITE,
    EXPEDIENTE,
    VALOR_TOTAL,
    VAL_IVA,
    CODI_DEPENDENCIA,
    CODI_AFILIADO,
    NOMBRE,
    CODI_BENEFICIARIO,
    NOMBRE_BENEFICIARIO,
    CANTIDAD_SERVICIO,
    DESCRIPCION_OBJECION,
    CANTIDAD_OBJECION,
    VAL_UNITARIO_OBJECION,
    VAL_TOTAL_OBJECION,
    VAL_IVA_OBJECION,
    OBSERVACION_OBJECION,
    OBSERVACION_CONCILIACION,
    OBSERVACION_NO_ACUERDO,
    OBSERVACION_NO_CONCILIABILIDAD,
    VAL_APROBADO_INI,
    VAL_LEVANTADO,
    VAL_NO_ACUERDO,
    VAL_NO_CONCILIABLE,
    FEC_RADICACION,
    FEC_AUDITORIA_PERTINENCIA,
    USUARIO_AUDITORIA_PERTINENCIA,
    FEC_AUDITORIA_LIQUIDACION,
    USUARIO_AUDITORIA_LIQUIDACION,
    FEC_NOTIFICACION,
    FEC_CONCILIACION,
    USUARIO_CONCILIACION,
    FEC_CIERRE,
    FEC_CALIDAD,
    USUARIO_CALIDAD,
    USUARIO_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    VAL_IVA_APROBADO,
    TIPO_BENEFICIARIO,
    CODI_TIPO_ATEN,
    CODI_ESTADO,
    FECH_RECEPCION,
    PARENTESCO,
    FEC_SERVICIO,
    VAL_APROBADO_APELACION,
    VAL_OBJETADO_FINAL,
    VAL_IVA_APROBADO_FINAL,
    VAL_APROBADO_FINAL,
    VAL_ISSFA,
    VAL_ISSPOL,
    VAL_IESS)
      SELECT
            E.ID_EXPEDIENTE,
    ID_TRAMITE,
    EXPEDIENTE,
    VALOR_TOTAL,
    VAL_IVA,
    CODI_DEPENDENCIA,
    CODI_AFILIADO,
    NOMBRE,
    CODI_BENEFICIARIO,
    NOMBRE_BENEFICIARIO,
    CANTIDAD_SERVICIO,
    DESCRIPCION_OBJECION,
    CANTIDAD_OBJECION,
    VAL_UNITARIO_OBJECION,
    VAL_TOTAL_OBJECION,
    VAL_IVA_OBJECION,
    OBSERVACION_OBJECION,
    OBSERVACION_CONCILIACION,
    OBSERVACION_NO_ACUERDO,
    OBSERVACION_NO_CONCILIABILIDAD,
    VAL_APROBADO_INI,
    VAL_LEVANTADO,
    VAL_NO_ACUERDO,
    VAL_NO_CONCILIABLE,
    FEC_RADICACION,
    FEC_AUDITORIA_PERTINENCIA,
    USUARIO_AUDITORIA_PERTINENCIA,
    FEC_AUDITORIA_LIQUIDACION,
    USUARIO_AUDITORIA_LIQUIDACION,
    FEC_NOTIFICACION,
    FEC_CONCILIACION,
    USUARIO_CONCILIACION,
    FEC_CIERRE,
    FEC_CALIDAD,
    USUARIO_CALIDAD,
    USUARIO_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    VAL_IVA_APROBADO,
    TIPO_BENEFICIARIO,
    CODI_TIPO_ATEN,
    CODI_ESTADO,
    FECH_RECEPCION,
    PARENTESCO,
    FEC_SERVICIO,
    VAL_APROBADO_APELACION,
    VAL_OBJETADO_FINAL,
    VAL_IVA_APROBADO_FINAL,
    VAL_APROBADO_FINAL,
    VAL_ISSFA,
    VAL_ISSPOL,
    VAL_IESS
        FROM AUD_EXPEDIENTES_T T3, TABLA31 T31, TABLA326@db1.com T32, Tabla33

        WHERE NOT EXISTS (SELECT 'X' FROM AUD_EXPEDIENTES_T@DBK_AUDIMED_DBREPLICA X4 WHERE X.ID_EXPEDIENTE = E.ID_EXPEDIENTE);

   L_EXPEDIENTES := SQL%ROWCOUNT;
   INSERT INTO AUD_VISOR_LOG_USUARIOS_T@DBK_AUDIMED_DBREPLICA (ID_LOG_USUARIO, ACCION,RESULTADO,DETALLE,USU_CREACION,FEC_CREACION,IP_EQUIPO,TABLA)
   VALUES(AUD_VISOR_LOG_USUARIOS_S.NEXTVAL@DBK_AUDIMED_DBREPLICA, 'REPLICA', 'EXITO', 'REPLICA DE EXPEDIENTES. REGISTROS:' ||TO_CHAR(L_EXPEDIENTES), 'SYSTEM', SYSDATE, L_IP,'AUD_EXPEDIENTES_T' );

   COMMIT;

   INSERT INTO AUD_SERVICIOS_T@DBK_AUDIMED_DBREPLICA
                                     NOLOGGING(ID_SERVICIO,
    ID_EXPEDIENTE,
    ID_TRAMITE,
    FEC_INICIO_SERVICIO,
    FEC_FIN_SERVICIO,
    FEC_ATENCION,
    DEPENDENCIA,
    CODI_PROCEDIMIENTO,
    NOMBRE_SIN_TARI,
    NUM_VALIDACION,
    EXAMEN,
    DERIVACION,
    CONTINGENCIA,
    MEDICO_TRATANTE,
    VAL_UNITARIO,
    VALOR_TOTAL,
    VALOR_IVA,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    CANTIDAD,
    CANTIDAD_OBJECION,
    VALOR_UNITARIO_OBJECION,
    VALOR_TOTAL_OBJECION,
    VALOR_IVA_OBJECION,
    OBS_OBJECION,
    OBS_CONCILIACION,
    OBS_NOACUERDO,
    OBS_NOCONCILIABLE,
    VALOR_ACEPTADO,
    VALOR_LEVANTADO,
    VALOR_NOACUERDO,
    VALOR_NOCONCILIABLE,
    FECH_RADICACION,
    FECH_AUDITORIA_PERTINENCIA,
    USU_AUDITORIA_PERTINENCIA,
    FECH_AUDITORIA_LIQUIDACION,
    USU_AUDITORIA_LIQUIDACION,
    FECH_NOTIFICACION,
    FECH_CONCILIACION,
    USU_CONCILIACION,
    FECH_CIERRE,
    FECH_CALIDAD,
    USU_CALIDAD,
    DIAGNOSTICO,
    DIAGNOSTICO_1,
    DIAGNOSTICO_2,
    DIAGNOSTICO_3,
    DIAGNOSTICO_4,
    DIAGNOSTICO_5)
      SELECT 
            S.ID_SERVICIO,
    ID_EXPEDIENTE,
    ID_TRAMITE,
    FEC_INICIO_SERVICIO,
    FEC_FIN_SERVICIO,
    FEC_ATENCION,
    DEPENDENCIA,
    CODI_PROCEDIMIENTO,
    NOMBRE_SIN_TARI,
    NUM_VALIDACION,
    EXAMEN,
    DERIVACION,
    CONTINGENCIA,
    MEDICO_TRATANTE,
    VAL_UNITARIO,
    VALOR_TOTAL,
    VALOR_IVA,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    CANTIDAD,
    CANTIDAD_OBJECION,
    VALOR_UNITARIO_OBJECION,
    VALOR_TOTAL_OBJECION,
    VALOR_IVA_OBJECION,
    OBS_OBJECION,
    OBS_CONCILIACION,
    OBS_NOACUERDO,
    OBS_NOCONCILIABLE,
    VALOR_ACEPTADO,
    VALOR_LEVANTADO,
    VALOR_NOACUERDO,
    VALOR_NOCONCILIABLE,
    FECH_RADICACION,
    FECH_AUDITORIA_PERTINENCIA,
    USU_AUDITORIA_PERTINENCIA,
    FECH_AUDITORIA_LIQUIDACION,
    USU_AUDITORIA_LIQUIDACION,
    FECH_NOTIFICACION,
    FECH_CONCILIACION,
    USU_CONCILIACION,
    FECH_CIERRE,
    FECH_CALIDAD,
    USU_CALIDAD,
    DIAGNOSTICO,
    DIAGNOSTICO_1,
    DIAGNOSTICO_2,
    DIAGNOSTICO_3,
    DIAGNOSTICO_4,
    DIAGNOSTICO_5
        FROM AUD_SERVICIOS_T S5 
        WHERE NOT EXISTS (SELECT 'X' FROM AUD_SERVICIOS_T@DBK_AUDIMED_DBREPLICA X6 WHERE X.ID_SERVICIO = S.ID_SERVICIO);

   L_SERVICIOS := SQL%ROWCOUNT;
   INSERT INTO AUD_VISOR_LOG_USUARIOS_T@DBK_AUDIMED_DBREPLICA (ID_LOG_USUARIO, ACCION,RESULTADO,DETALLE,USU_CREACION,FEC_CREACION,IP_EQUIPO,TABLA)
   VALUES(AUD_VISOR_LOG_USUARIOS_S.NEXTVAL@DBK_AUDIMED_DBREPLICA, 'REPLICA', 'EXITO', 'REPLICA DE SERVICIOS DE EXPEDIENTES. REGISTROS:' ||TO_CHAR(L_SERVICIOS), 'SYSTEM', SYSDATE, L_IP,'AUD_SERVICIOS_T' );

   COMMIT;

  
   INSERT INTO AUD_TRAZA_ACCIONES_T@DBK_AUDIMED_DBREPLICA
                                     NOLOGGING(ID_TRAZA,
    ACCION,
    ID_TRAMITE,
    ID_EXPEDIENTE,
    ID_SERVICIO,
    MODULO,
    DETALLE,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    TABLA,
    CAMPO,
    VAL_ANTERIOR,
    VAL_NUEVO)
      SELECT T.ID_TRAZA,
    ACCION,
    ID_TRAMITE,
    ID_EXPEDIENTE,
    ID_SERVICIO,
    MODULO,
    DETALLE,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    TABLA,
    CAMPO,
    VAL_ANTERIOR,
    VAL_NUEVO
        FROM AUD_TRAZA_ACCIONES_T T7 
                WHERE NOT EXISTS (SELECT 'X' FROM AUD_TRAZA_ACCIONES_T@DBK_AUDIMED_DBREPLICA X8 WHERE X.ID_TRAZA = T.ID_TRAZA);
    L_TRAZABILIDAD := SQL%ROWCOUNT;
    INSERT INTO AUD_VISOR_LOG_USUARIOS_T@DBK_AUDIMED_DBREPLICA (ID_LOG_USUARIO, ACCION,RESULTADO,DETALLE,USU_CREACION,FEC_CREACION,IP_EQUIPO,TABLA)
    VALUES(AUD_VISOR_LOG_USUARIOS_S.NEXTVAL@DBK_AUDIMED_DBREPLICA, 'REPLICA', 'EXITO', 'REPLICA DE TRAZABILIDAD. REGISTROS:' ||TO_CHAR(L_TRAZABILIDAD), 'SYSTEM', SYSDATE, L_IP,'AUD_TRAZA_ACCIONES_T' );

    COMMIT;

   INSERT INTO AUD_VISOR_LOG_USUARIOS_T@DBK_AUDIMED_DBREPLICA (ID_LOG_USUARIO, ACCION,RESULTADO,DETALLE,USU_CREACION,FEC_CREACION,IP_EQUIPO,TABLA)
   VALUES(AUD_VISOR_LOG_USUARIOS_S.NEXTVAL@DBK_AUDIMED_DBREPLICA, 'REPLICA', 'EXITO', 'ENVIO DE NOTIFICACION', 'SYSTEM', SYSDATE, L_IP, NULL );

 
   L_FECHAFIN := SYSDATE;
   L_MENERR := 'RESUMEN DEL PROCESO DE REPLICA '
      || CHR (13)
      || 'PROCESO DE REPLICA DE AUDITORIAS MEDICAS AUDIMED EJECUTADO CON EXITO.'
      || CHR (13)
      || 'TRAMITES PROCESADOS:' || TO_CHAR(L_TRAMITES) 
      || CHR (13)
      || 'EXPEDIENTES PROCESADOS:' || TO_CHAR(L_EXPEDIENTES) 
      || CHR (13)
      || 'SERVICIOS PROCESADOS:' || TO_CHAR(L_SERVICIOS) 
      || CHR (13)
      || 'TRAZABILIDAD PROCESADOS:' || TO_CHAR(L_TRAZABILIDAD) 
      || CHR (13)
      || 'TOTAL DE REGISTROS PROCESADOS:' || TO_CHAR(L_TRAMITES + L_EXPEDIENTES + L_SERVICIOS + L_TRAZABILIDAD)
      || CHR (13)
      || 'INICIO DE EJECUCION:' || TO_CHAR(L_FECHAINI,'YYYY-MM-DD HH24:MI:SS')
      || CHR (13)
      || 'FIN DE EJECUCION:' || TO_CHAR(L_FECHAFIN,'YYYY-MM-DD HH24:MI:SS');

   AO_MENSAJESALIDA := L_MENERR;
   AO_REGISTROS := L_TRAMITES + L_EXPEDIENTES + L_SERVICIOS + L_TRAZABILIDAD;
   SYS.DBMS_OUTPUT.PUT_LINE(L_MENERR);

   INSERT INTO AUD_VISOR_LOG_USUARIOS_T@DBK_AUDIMED_DBREPLICA (ID_LOG_USUARIO, ACCION,RESULTADO,DETALLE,USU_CREACION,FEC_CREACION,IP_EQUIPO,TABLA)
   VALUES(AUD_VISOR_LOG_USUARIOS_S.NEXTVAL@DBK_AUDIMED_DBREPLICA, 'REPLICA', 'EXITO', 'FIN DEL PROCESO', 'SYSTEM', SYSDATE, L_IP,NULL );
   COMMIT;
   SYS.DBMS_APPLICATION_INFO.SET_MODULE (NULL, NULL);

EXCEPTION
   WHEN OTHERS
   THEN
      ROLLBACK;

      L_MENERR := 'ERROR GENERAL: ' || SUBSTR (SQLERRM, 1, 4000);
      INSERT INTO AUD_VISOR_LOG_USUARIOS_T@DBK_AUDIMED_DBREPLICA (ID_LOG_USUARIO, ACCION,RESULTADO,DETALLE,USU_CREACION,FEC_CREACION,IP_EQUIPO,TABLA)
      VALUES(AUD_VISOR_LOG_USUARIOS_S.NEXTVAL@DBK_AUDIMED_DBREPLICA, 'REPLICA', 'ERROR', SUBSTR(L_MENERR,1,1000), 'SYSTEM', SYSDATE, L_IP,NULL );

      AO_MENSAJESALIDA := L_MENERR;
      SYS.DBMS_APPLICATION_INFO.SET_MODULE (NULL, NULL);
END SAL_REPLICAAUDIMED_P;